# Generated by Django 5.1.4 on 2024-12-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_limit', models.IntegerField(default=5, help_text='Número máximo de intentos fallidos de acceso')),
            ],
        ),
    ]
