# Generated by Django 5.1.4 on 2024-12-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Desayunos', 'Desayunos'), ('Comidas', 'Comidas'), ('Postres', 'Postres'), ('Bebidas', 'Bebidas')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('Fácil', 'Fácil'), ('Media', 'Media'), ('Difícil', 'Difícil')], max_length=20),
        ),
    ]
